[project]
name = "colombian-judicial-distircts-choropleth-map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "camelot-py>=2.0.0",
    "fastexcel>=0.21.0",
    "fiona>=1.10.1",
    "geopandas>=1.2.0",
    "ipykernel>=7.4.0",
    "ipynbname>=2025.8.0.0",
    "ipython>=9.17.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pyarrow>=25.0.1",
    "pyogrio>=0.13.0",
    "pypdf>=6.19.0",
    "pyproj>=3.8.0",
    "pytest>=9.1.1",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.4",
    "pyyaml>=6.0.3",
    "shapely>=2.1.2",
    "xlrd>=2.0.2",
    "xlsxwriter>=3.2.9",
]
